# Building with jdk11 and running tests with jdk8,
# see https://github.com/apache/shardingsphere/blob/master/.github/workflows/ci.yml

variables:
  JDK_BUILD_IMAGE: registry.red-soft.biz:5000/jdk/temurin-11-jdk
  JDK_TEST_IMAGE: registry.red-soft.biz:5000/jdk/temurin-8-jdk
  RELEASEHUB_CLIENT_IMAGE: registry.red-soft.biz:5000/utils/red-release-manager/client:master
  MAVEN_OPTS: "-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dspotless.apply.skip=true"

stages:
  - prepare
  - build
  - test
  - deploy


workflow:
  rules:
    when: never

build_project:
  tags: ["docker", "linux"]
  stage: build
  image: $JDK_BUILD_IMAGE
  script:
    - ./mvnw clean install -Prelease -T1C -DskipTests -Djacoco.skip=true -Dcheckstyle.skip=true -Drat.skip=true -Dmaven.javadoc.skip=true -B
  artifacts:
    paths: [
      "distribution/jdbc/target/",
      "distribution/proxy/target/",
      "distribution/agent/target"
    ]

# relhub deploy example:
# http://git.red-soft.biz/red-database/red-database/-/blob/master/.gitlab-ci.yml#L779

# TODO: add release hub key (client pulls it from system envvars)
deploy_to_release_hub:
  stage: deploy
  tags: ["docker", "x86_64"]
  image: $RELEASEHUB_CLIENT_IMAGE