# Building with jdk11 and running tests with jdk8,
# see https://github.com/apache/shardingsphere/blob/master/.github/workflows/ci.yml

variables:
  JDK_BUILD_IMAGE: registry.red-soft.biz:5000/jdk/temurin-11-jdk
  JDK_TEST_IMAGE: registry.red-soft.biz:5000/jdk/temurin-8-jdk
  RELEASEHUB_CLIENT_IMAGE: registry.red-soft.biz:5000/utils/red-release-manager/client:master
  M2_DIR: /root/.m2
  M2_SETTINGSFILE: ${CI_PROJECT_DIR}/ci/settings.xml
  MAVEN_OPTS: "-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dspotless.apply.skip=true"

stages:
  - prepare
  - build
  - test
  - deploy


workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
    - if: $CI_PIPELINE_SOURCE == "push"

prepare_build_env:
  tags: ["docker", "linux", "x86_64"]
  stage: prepare
  image: $JDK_BUILD_IMAGE
  script:
    - apt update && DEBIAN_FRONTEND=noninteractive apt install -y libxml2-utils m4
    - echo PROJECT_VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml) >> build.env
    - m4 -DRSHRD_VERSION=${PROJECT_VERSION} ci/artifacts.m4 >> ci/artifacts
  artifacts:
    reports:
      dotenv: build.env
    paths:
      - ci/artifacts

build_java11:
  tags: ["docker", "linux", "x86_64"]
  stage: build
  image: $JDK_BUILD_IMAGE
  variables:
    ARTIFACTS_DIR: ${CI_PROJECT_DIR}/${PROJECT_VERSION}
  script:
    - ./mvnw -s ${M2_SETTINGSFILE} clean install -Prelease -T1C -DskipTests -Djacoco.skip=true -Dcheckstyle.skip=true -Drat.skip=true -Dmaven.javadoc.skip=true -B
    - mkdir -pv ${ARTIFACTS_DIR}
    - cp -v distribution/{jdbc,proxy,agent}/target/*.{tar.gz,tar.gz.sha512} ${ARTIFACTS_DIR}
  artifacts:
    paths:
      - ${ARTIFACTS_DIR}
  dependencies:
    - prepare_build_env

test_java8:
  tags: ["docker", "linux", "x86_64"]
  stage: test
  image: $JDK_TEST_IMAGE
  dependencies:
    - build_java11
  script:
    - ./mvnw -s ${M2_SETTINGSFILE} install -T1C -B -ntp -fae
  allow_failure: true

# relhub deploy example:
# http://git.red-soft.biz/red-database/red-database/-/blob/master/.gitlab-ci.yml#L779

# TODO: add release hub key (client pulls it from system envvars)
deploy_to_release_hub:
  stage: deploy
  tags: ["docker", "x86_64", "linux"]
  image: $RELEASEHUB_CLIENT_IMAGE
  script:
    - relmanager_client deploy rshrd ${PROJECT_VERSION} --artifacts ci/artifacts --ci-url ${CI_URL} --context ${BUILD_TYPE}
  only:
    variables:
      - $RELEASE_HUB_KEY