-- For MySQL,PostgreSQL,SQLServer
CREATE DATABASE dbtbl_0;
CREATE DATABASE dbtbl_1;
CREATE DATABASE dbtbl_2;
CREATE DATABASE dbtbl_3;
CREATE DATABASE dbtbl_4;
CREATE DATABASE dbtbl_5;
CREATE DATABASE dbtbl_6;
CREATE DATABASE dbtbl_7;
CREATE DATABASE dbtbl_8;
CREATE DATABASE dbtbl_9;
CREATE DATABASE db_0;
CREATE DATABASE db_1;
CREATE DATABASE db_2;
CREATE DATABASE db_3;
CREATE DATABASE db_4;
CREATE DATABASE db_5;
CREATE DATABASE db_6;
CREATE DATABASE db_7;
CREATE DATABASE db_8;
CREATE DATABASE db_9;
CREATE DATABASE tbl;
CREATE DATABASE nullable_0;
CREATE DATABASE nullable_1;
CREATE DATABASE nullable_2;
CREATE DATABASE nullable_3;
CREATE DATABASE nullable_4;
CREATE DATABASE nullable_5;
CREATE DATABASE nullable_6;
CREATE DATABASE nullable_7;
CREATE DATABASE nullable_8;
CREATE DATABASE nullable_9;
CREATE DATABASE master_0;
CREATE DATABASE master_1;
CREATE DATABASE master_2;
CREATE DATABASE master_3;
CREATE DATABASE master_4;
CREATE DATABASE master_5;
CREATE DATABASE master_6;
CREATE DATABASE master_7;
CREATE DATABASE master_8;
CREATE DATABASE master_9;
CREATE DATABASE slave_0;
CREATE DATABASE slave_1;
CREATE DATABASE slave_2;
CREATE DATABASE slave_3;
CREATE DATABASE slave_4;
CREATE DATABASE slave_5;
CREATE DATABASE slave_6;
CREATE DATABASE slave_7;
CREATE DATABASE slave_8;
CREATE DATABASE slave_9;
CREATE DATABASE jdbc_0;
CREATE DATABASE jdbc_1;
CREATE DATABASE master_only;
CREATE DATABASE slave_only;

-- For Oracle
create user jdbc identified by jdbc;
create tablespace jdbc datafile '${YOUR_SPACE}/jdbc.dbf' size 200M;
alter user jdbc default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to jdbc;
create user dbtbl_0 identified by dbtbl_0;
alter user dbtbl_0 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to dbtbl_0;
create user dbtbl_1 identified by dbtbl_1;
alter user dbtbl_1 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to dbtbl_1;
create user dbtbl_2 identified by dbtbl_2;
alter user dbtbl_2 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to dbtbl_2;
create user dbtbl_3 identified by dbtbl_3;
alter user dbtbl_3 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to dbtbl_3;
create user dbtbl_4 identified by dbtbl_4;
alter user dbtbl_4 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to dbtbl_4;
create user dbtbl_5 identified by dbtbl_5;
alter user dbtbl_5 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to dbtbl_5;
create user dbtbl_6 identified by dbtbl_6;
alter user dbtbl_6 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to dbtbl_6;
create user dbtbl_7 identified by dbtbl_7;
alter user dbtbl_7 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to dbtbl_7;
create user dbtbl_8 identified by dbtbl_8;
alter user dbtbl_8 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to dbtbl_8;
create user dbtbl_9 identified by dbtbl_9;
alter user dbtbl_9 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to dbtbl_9;
create user db_0 identified by db_0;
alter user db_0 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to db_0;
create user db_1 identified by db_1;
alter user db_1 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to db_1;
create user db_2 identified by db_2;
alter user db_2 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to db_2;
create user db_3 identified by db_3;
alter user db_3 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to db_3;
create user db_4 identified by db_4;
alter user db_4 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to db_4;
create user db_5 identified by db_5;
alter user db_5 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to db_5;
create user db_6 identified by db_6;
alter user db_6 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to db_6;
create user db_7 identified by db_7;
alter user db_7 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to db_7;
create user db_8 identified by db_8;
alter user db_8 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to db_8;
create user db_9 identified by db_9;
alter user db_9 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to db_9;
create user nullable_0 identified by nullable_0;
alter user nullable_0 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to nullable_0;
create user nullable_1 identified by nullable_1;
alter user nullable_1 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to nullable_1;
create user nullable_2 identified by nullable_2;
alter user nullable_2 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to nullable_2;
create user nullable_3 identified by nullable_3;
alter user nullable_3 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to nullable_3;
create user nullable_4 identified by nullable_4;
alter user nullable_4 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to nullable_4;
create user nullable_5 identified by nullable_5;
alter user nullable_5 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to nullable_5;
create user nullable_6 identified by nullable_6;
alter user nullable_6 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to nullable_6;
create user nullable_7 identified by nullable_7;
alter user nullable_7 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to nullable_7;
create user nullable_8 identified by nullable_8;
alter user nullable_8 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to nullable_8;
create user nullable_9 identified by nullable_9;
alter user nullable_9 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to nullable_9;
create user master_0 identified by master_0;
alter user master_0 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to master_0;
create user master_1 identified by master_1;
alter user master_1 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to master_1;
create user master_2 identified by master_2;
alter user master_2 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to master_2;
create user master_3 identified by master_3;
alter user master_3 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to master_3;
create user master_4 identified by master_4;
alter user master_4 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to master_4;
create user master_5 identified by master_5;
alter user master_5 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to master_5;
create user master_6 identified by master_6;
alter user master_6 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to master_6;
create user master_7 identified by master_7;
alter user master_7 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to master_7;
create user master_8 identified by master_8;
alter user master_8 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to master_8;
create user master_9 identified by master_9;
alter user master_9 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to master_9;
create user slave_0 identified by slave_0;
alter user slave_0 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to slave_0;
create user slave_1 identified by slave_1;
alter user slave_1 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to slave_1;
create user slave_2 identified by slave_2;
alter user slave_2 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to slave_2;
create user slave_3 identified by slave_3;
alter user slave_3 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to slave_3;
create user slave_4 identified by slave_4;
alter user slave_4 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to slave_4;
create user slave_5 identified by slave_5;
alter user slave_5 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to slave_5;
create user slave_6 identified by slave_6;
alter user slave_6 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to slave_6;
create user slave_7 identified by slave_7;
alter user slave_7 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to slave_7;
create user slave_8 identified by slave_8;
alter user slave_8 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to slave_8;
create user slave_9 identified by slave_9;
alter user slave_9 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to slave_9;
create user master_only identified by master_only;
alter user master_only default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to master_only;
create user slave_only identified by slave_only;
alter user slave_only default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to slave_only;
create user jdbc_0 identified by jdbc_0;
alter user jdbc_0 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to jdbc_0;
create user jdbc_1 identified by jdbc_1;
alter user jdbc_1 default tablespace jdbc;
grant create session,create table,create view,create sequence,unlimited tablespace to jdbc_1;