CREATE SCHEMA IF NOT EXISTS ds_jdbc_0;
CREATE SCHEMA IF NOT EXISTS ds_jdbc_1;
CREATE SCHEMA IF NOT EXISTS ds_jdbc_master_0;
CREATE SCHEMA IF NOT EXISTS ds_jdbc_master_0_slave_0;
CREATE SCHEMA IF NOT EXISTS ds_jdbc_master_0_slave_1;
CREATE SCHEMA IF NOT EXISTS ds_jdbc_master_1;
CREATE SCHEMA IF NOT EXISTS ds_jdbc_master_1_slave_0;
CREATE SCHEMA IF NOT EXISTS ds_jdbc_master_1_slave_1;

CREATE SCHEMA IF NOT EXISTS ds_jdbc;
CREATE SCHEMA IF NOT EXISTS ds_jdbc_master;
CREATE SCHEMA IF NOT EXISTS ds_jdbc_slave_0;
CREATE SCHEMA IF NOT EXISTS ds_jdbc_slave_1;