CREATE <#if relpersistence>UNLOGGED </#if>TABLE IF NOT EXISTS ${schema}.${name}
(
<#if columns?? && columns?size gt 0 >
<#list columns as c >
<#if c.name?? && c.cltype?? >
${c.name} ${c.displaytypname}<#if c.collspcname?? && c.collspcname?length gt 0 > COLLATE ${c.collspcname}</#if><#if c.attnotnull > NOT NULL</#if><#if c.defval?? && c.defval?length gt 0 && c.colconstype != 'g' > DEFAULT ${c.defval}</#if>
<#if c.colconstype = 'n' && c.attidentity?? && c.attidentity != '' >
<#if c.attidentity = 'a' > GENERATED ALWAYS AS IDENTITY<#elseif c.attidentity == 'd' > GENERATED BY DEFAULT AS IDENTITY</#if>
<#if c.seqincrement?? || c.seqcycle?? || c.seqincrement?? || c.seqstart?? || c.seqmin?? || c.seqmax?? || c.seqcache?? > ( </#if>
<#if c.seqcycle?? >
CYCLE </#if><#if c.seqincrement?? && c.seqincrement gt -1 >
INCREMENT ${c.seqincrement} </#if><#if c.seqstart?? && c.seqstart gt -1>
START ${c.seqstart} </#if><#if c.seqmin?? && c.seqmin gt -1>
MINVALUE ${c.seqmin??} </#if><#if c.seqmax?? && c.seqmax gt -1>
MAXVALUE ${c.seqmax??} </#if><#if c.seqcache?? && c.seqcache gt -1>
CACHE ${c.seqcache} </#if>
<#if c.seqincrement?? || c.seqcycle?? || c.seqincrement?? || c.seqstart?? || c.seqmin?? || c.seqmax?? || c.seqcache?? >)</#if>
</#if>
<#if c.colconstype = 'g' && c.genexpr?? && c.genexpr != '' > GENERATED ALWAYS AS (${c.genexpr??}) STORED</#if>
<#if c?counter lt columns?size>,
</#if>
</#if>
</#list >
</#if>
)