DROP SCHEMA IF EXISTS `trans_log`;
DROP SCHEMA IF EXISTS `ds_trans_0`;
DROP SCHEMA IF EXISTS `ds_trans_1`;

CREATE SCHEMA IF NOT EXISTS `trans_log`;
CREATE SCHEMA IF NOT EXISTS `ds_trans_0`;
CREATE SCHEMA IF NOT EXISTS `ds_trans_1`;
