// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.shardingjdbc.orchestration.reg.etcd.internal.stub;

public interface AuthEnableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.AuthEnableRequest)
    com.google.protobuf.MessageOrBuilder {
}
