// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.shardingjdbc.orchestration.reg.etcd.internal.stub;

public interface AuthUserListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.AuthUserListRequest)
    com.google.protobuf.MessageOrBuilder {
}
