// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.shardingjdbc.orchestration.reg.etcd.internal.stub;

public interface AuthDisableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.AuthDisableRequest)
    com.google.protobuf.MessageOrBuilder {
}
