// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package io.shardingjdbc.orchestration.reg.etcd.internal.stub;

public interface PermissionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authpb.Permission)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.authpb.Permission.Type permType = 1;</code>
   */
  int getPermTypeValue();
  /**
   * <code>.authpb.Permission.Type permType = 1;</code>
   */
  Permission.Type getPermType();

  /**
   * <code>bytes key = 2;</code>
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>bytes range_end = 3;</code>
   */
  com.google.protobuf.ByteString getRangeEnd();
}
