// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.shardingjdbc.orchestration.reg.etcd.internal.stub;

/**
 * Protobuf type {@code etcdserverpb.StatusResponse}
 */
public  final class StatusResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:etcdserverpb.StatusResponse)
    StatusResponseOrBuilder {
  public static final int HEADER_FIELD_NUMBER = 1;
  public static final int VERSION_FIELD_NUMBER = 2;
  public static final int DBSIZE_FIELD_NUMBER = 3;
  public static final int LEADER_FIELD_NUMBER = 4;
  public static final int RAFTINDEX_FIELD_NUMBER = 5;
  public static final int RAFTTERM_FIELD_NUMBER = 6;
private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:etcdserverpb.StatusResponse)
  private static final StatusResponse DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<StatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<StatusResponse>() {
    public StatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new StatusResponse(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new StatusResponse();
  }

  private ResponseHeader header_;
  private volatile Object version_;
  private long dbSize_;
  private long leader_;
  private long raftIndex_;
  private long raftTerm_;
  private byte memoizedIsInitialized = -1;
  // Use StatusResponse.newBuilder() to construct.
  private StatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StatusResponse() {
    version_ = "";
    dbSize_ = 0L;
    leader_ = 0L;
    raftIndex_ = 0L;
    raftTerm_ = 0L;
  }

  private StatusResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            ResponseHeader.Builder subBuilder = null;
            if (header_ != null) {
              subBuilder = header_.toBuilder();
            }
            header_ = input.readMessage(ResponseHeader.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(header_);
              header_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 24: {

            dbSize_ = input.readInt64();
            break;
          }
          case 32: {

            leader_ = input.readUInt64();
            break;
          }
          case 40: {

            raftIndex_ = input.readUInt64();
            break;
          }
          case 48: {

            raftTerm_ = input.readUInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EtcdProto.internal_static_etcdserverpb_StatusResponse_descriptor;
  }

  public static StatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static StatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static StatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static StatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static StatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static StatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static StatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static StatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static StatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static StatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static StatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static StatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(StatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static StatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<StatusResponse> parser() {
    return PARSER;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EtcdProto.internal_static_etcdserverpb_StatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            StatusResponse.class, Builder.class);
  }

  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  public boolean hasHeader() {
    return header_ != null;
  }

  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  public ResponseHeader getHeader() {
    return header_ == null ? ResponseHeader.getDefaultInstance() : header_;
  }

  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  public ResponseHeaderOrBuilder getHeaderOrBuilder() {
    return getHeader();
  }

  /**
   * <pre>
   * version is the cluster protocol version used by the responding member.
   * </pre>
   *
   * <code>string version = 2;</code>
   */
  public String getVersion() {
    Object ref = version_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }

  /**
   * <pre>
   * version is the cluster protocol version used by the responding member.
   * </pre>
   *
   * <code>string version = 2;</code>
   */
  public com.google.protobuf.ByteString
      getVersionBytes() {
    Object ref = version_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <pre>
   * dbSize is the size of the backend database, in bytes, of the responding member.
   * </pre>
   *
   * <code>int64 dbSize = 3;</code>
   */
  public long getDbSize() {
    return dbSize_;
  }

  /**
   * <pre>
   * leader is the member ID which the responding member believes is the current leader.
   * </pre>
   *
   * <code>uint64 leader = 4;</code>
   */
  public long getLeader() {
    return leader_;
  }

  /**
   * <pre>
   * raftIndex is the current raft index of the responding member.
   * </pre>
   *
   * <code>uint64 raftIndex = 5;</code>
   */
  public long getRaftIndex() {
    return raftIndex_;
  }

  /**
   * <pre>
   * raftTerm is the current raft term of the responding member.
   * </pre>
   *
   * <code>uint64 raftTerm = 6;</code>
   */
  public long getRaftTerm() {
    return raftTerm_;
  }

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
    }
    if (dbSize_ != 0L) {
      output.writeInt64(3, dbSize_);
    }
    if (leader_ != 0L) {
      output.writeUInt64(4, leader_);
    }
    if (raftIndex_ != 0L) {
      output.writeUInt64(5, raftIndex_);
    }
    if (raftTerm_ != 0L) {
      output.writeUInt64(6, raftTerm_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
    }
    if (dbSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, dbSize_);
    }
    if (leader_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, leader_);
    }
    if (raftIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, raftIndex_);
    }
    if (raftTerm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, raftTerm_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof StatusResponse)) {
      return super.equals(obj);
    }
    StatusResponse other = (StatusResponse) obj;

    boolean result = true;
    result = result && (hasHeader() == other.hasHeader());
    if (hasHeader()) {
      result = result && getHeader()
          .equals(other.getHeader());
    }
    result = result && getVersion()
        .equals(other.getVersion());
    result = result && (getDbSize()
        == other.getDbSize());
    result = result && (getLeader()
        == other.getLeader());
    result = result && (getRaftIndex()
        == other.getRaftIndex());
    result = result && (getRaftTerm()
        == other.getRaftTerm());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + DBSIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDbSize());
    hash = (37 * hash) + LEADER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLeader());
    hash = (37 * hash) + RAFTINDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRaftIndex());
    hash = (37 * hash) + RAFTTERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRaftTerm());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public Builder newBuilderForType() { return newBuilder(); }

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @Override
  public com.google.protobuf.Parser<StatusResponse> getParserForType() {
    return PARSER;
  }

  public StatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code etcdserverpb.StatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:etcdserverpb.StatusResponse)
      StatusResponseOrBuilder {
    private ResponseHeader header_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        ResponseHeader, ResponseHeader.Builder, ResponseHeaderOrBuilder> headerBuilder_;
    private Object version_ = "";
    private long dbSize_ ;
    private long leader_ ;
    private long raftIndex_ ;
    private long raftTerm_ ;

    // Construct using io.shardingjdbc.orchestration.reg.etcd.internal.stub.StatusResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EtcdProto.internal_static_etcdserverpb_StatusResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EtcdProto.internal_static_etcdserverpb_StatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StatusResponse.class, Builder.class);
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }

    public Builder clear() {
      super.clear();
      if (headerBuilder_ == null) {
        header_ = null;
      } else {
        header_ = null;
        headerBuilder_ = null;
      }
      version_ = "";

      dbSize_ = 0L;

      leader_ = 0L;

      raftIndex_ = 0L;

      raftTerm_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EtcdProto.internal_static_etcdserverpb_StatusResponse_descriptor;
    }

    public StatusResponse getDefaultInstanceForType() {
      return StatusResponse.getDefaultInstance();
    }

    public StatusResponse build() {
      StatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public StatusResponse buildPartial() {
      StatusResponse result = new StatusResponse(this);
      if (headerBuilder_ == null) {
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      result.version_ = version_;
      result.dbSize_ = dbSize_;
      result.leader_ = leader_;
      result.raftIndex_ = raftIndex_;
      result.raftTerm_ = raftTerm_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }

    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }

    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof StatusResponse) {
        return mergeFrom((StatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(StatusResponse other) {
      if (other == StatusResponse.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (other.getDbSize() != 0L) {
        setDbSize(other.getDbSize());
      }
      if (other.getLeader() != 0L) {
        setLeader(other.getLeader());
      }
      if (other.getRaftIndex() != 0L) {
        setRaftIndex(other.getRaftIndex());
      }
      if (other.getRaftTerm() != 0L) {
        setRaftTerm(other.getRaftTerm());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      StatusResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (StatusResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return headerBuilder_ != null || header_ != null;
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public ResponseHeader getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? ResponseHeader.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public Builder setHeader(
        ResponseHeader.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
        onChanged();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public Builder setHeader(ResponseHeader value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
        onChanged();
      } else {
        headerBuilder_.setMessage(value);
      }

      return this;
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public Builder mergeHeader(ResponseHeader value) {
      if (headerBuilder_ == null) {
        if (header_ != null) {
          header_ =
            ResponseHeader.newBuilder(header_).mergeFrom(value).buildPartial();
        } else {
          header_ = value;
        }
        onChanged();
      } else {
        headerBuilder_.mergeFrom(value);
      }

      return this;
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = null;
        onChanged();
      } else {
        header_ = null;
        headerBuilder_ = null;
      }

      return this;
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public ResponseHeader.Builder getHeaderBuilder() {

      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public ResponseHeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            ResponseHeader.getDefaultInstance() : header_;
      }
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ResponseHeader, ResponseHeader.Builder, ResponseHeaderOrBuilder>
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ResponseHeader, ResponseHeader.Builder, ResponseHeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    /**
     * <pre>
     * version is the cluster protocol version used by the responding member.
     * </pre>
     *
     * <code>string version = 2;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <pre>
     * version is the cluster protocol version used by the responding member.
     * </pre>
     *
     * <code>string version = 2;</code>
     */
    public Builder setVersion(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      version_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * version is the cluster protocol version used by the responding member.
     * </pre>
     *
     * <code>string version = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     * version is the cluster protocol version used by the responding member.
     * </pre>
     *
     * <code>string version = 2;</code>
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      version_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * version is the cluster protocol version used by the responding member.
     * </pre>
     *
     * <code>string version = 2;</code>
     */
    public Builder clearVersion() {

      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }

    /**
     * <pre>
     * dbSize is the size of the backend database, in bytes, of the responding member.
     * </pre>
     *
     * <code>int64 dbSize = 3;</code>
     */
    public long getDbSize() {
      return dbSize_;
    }

    /**
     * <pre>
     * dbSize is the size of the backend database, in bytes, of the responding member.
     * </pre>
     *
     * <code>int64 dbSize = 3;</code>
     */
    public Builder setDbSize(long value) {

      dbSize_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * dbSize is the size of the backend database, in bytes, of the responding member.
     * </pre>
     *
     * <code>int64 dbSize = 3;</code>
     */
    public Builder clearDbSize() {

      dbSize_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * leader is the member ID which the responding member believes is the current leader.
     * </pre>
     *
     * <code>uint64 leader = 4;</code>
     */
    public long getLeader() {
      return leader_;
    }

    /**
     * <pre>
     * leader is the member ID which the responding member believes is the current leader.
     * </pre>
     *
     * <code>uint64 leader = 4;</code>
     */
    public Builder setLeader(long value) {

      leader_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * leader is the member ID which the responding member believes is the current leader.
     * </pre>
     *
     * <code>uint64 leader = 4;</code>
     */
    public Builder clearLeader() {

      leader_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * raftIndex is the current raft index of the responding member.
     * </pre>
     *
     * <code>uint64 raftIndex = 5;</code>
     */
    public long getRaftIndex() {
      return raftIndex_;
    }

    /**
     * <pre>
     * raftIndex is the current raft index of the responding member.
     * </pre>
     *
     * <code>uint64 raftIndex = 5;</code>
     */
    public Builder setRaftIndex(long value) {

      raftIndex_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * raftIndex is the current raft index of the responding member.
     * </pre>
     *
     * <code>uint64 raftIndex = 5;</code>
     */
    public Builder clearRaftIndex() {

      raftIndex_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * raftTerm is the current raft term of the responding member.
     * </pre>
     *
     * <code>uint64 raftTerm = 6;</code>
     */
    public long getRaftTerm() {
      return raftTerm_;
    }
    /**
     * <pre>
     * raftTerm is the current raft term of the responding member.
     * </pre>
     *
     * <code>uint64 raftTerm = 6;</code>
     */
    public Builder setRaftTerm(long value) {

      raftTerm_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * raftTerm is the current raft term of the responding member.
     * </pre>
     *
     * <code>uint64 raftTerm = 6;</code>
     */
    public Builder clearRaftTerm() {

      raftTerm_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:etcdserverpb.StatusResponse)
  }

}

