// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package io.shardingjdbc.orchestration.reg.etcd.internal.stub;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authpb.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes name = 1;</code>
   */
  com.google.protobuf.ByteString getName();

  /**
   * <code>bytes password = 2;</code>
   */
  com.google.protobuf.ByteString getPassword();

  /**
   * <code>repeated string roles = 3;</code>
   */
  java.util.List<String>
      getRolesList();
  /**
   * <code>repeated string roles = 3;</code>
   */
  int getRolesCount();
  /**
   * <code>repeated string roles = 3;</code>
   */
  String getRoles(int index);
  /**
   * <code>repeated string roles = 3;</code>
   */
  com.google.protobuf.ByteString
      getRolesBytes(int index);
}
