#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/ci.yml'
      - '.github/workflows/reusable-global-environment.yml'
      - '.github/actions/setup-build-environment/**'
      - 'mvnw'
      - '.mvn/**'
      - '**/pom.xml'
      - '**/src/main/**'
      - '**/src/test/**'
      - '!distribution/**'
      - 'test/it/**'
      - '!test/e2e/**'
      - 'test/e2e/driver/**'
      - '!**/*.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  MAVEN_ARGS: -B -ntp -fae -e
  MAVEN_OPTS: -Dhttp.keepAlive=false

jobs:
  global-environment:
    name: Import Global Environment
    uses: ./.github/workflows/reusable-global-environment.yml

  ci:
    name: CI
    needs: global-environment
    if: ${{ needs.global-environment.outputs.GLOBAL_JOB_ENABLED == 'true' }}
    runs-on: ${{ needs.global-environment.outputs.GLOBAL_RUNS_ON }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: ./.github/actions/setup-build-environment
      - name: Build and Run Tests
        run: ./mvnw clean install -T1C
